version: 0.0
os: linux
files: 
  - source: /
    destination: /home/ubuntu/elbuenconejo-backend
permissions:
  - object: /home/ubuntu/elbuenconejo-backend
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStop:
      - location: scripts/deploy/stop_app.sh
        timeout: 300
        runas: ubuntu
  BeforeInstall:
      - location: scripts/deploy/clean_instance.sh
        timeout: 300
        runas: ubuntu
  AfterInstall:
      - location: scripts/deploy/instance_os_dependencies.sh
        timeout: 300
        runas: ubuntu
      - location: scripts/deploy/python_dependencies.sh
        timeout: 300
        runas: ubuntu
      - location: scripts/deploy/gunicorn.sh
        timeout: 300
        runas: ubuntu
      - location: scripts/deploy/nginx.sh
        timeout: 300
        runas: ubuntu
  ApplicationStart:
      - location: scripts/deploy/start_app.sh
        timeout: 300
        runas: ubuntu
  
  