# Generated by Django 4.2.6 on 2024-09-18 21:47

import apps.cages.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_cages", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cage",
            name="photo",
            field=models.URLField(
                default="/images/granja.jpg",
                max_length=500,
                validators=[apps.cages.models.file_validation],
            ),
        ),
    ]
