version: 0.0
os: linux 
files:
  - source: /backend/rabbits_farm/
    destination: /home/ubuntu/rabbits_farm
  - source: /backend/apps/
    destination: /home/ubuntu/apps
  - source: /manage.py
    destination: /home/ubuntu
  - source: /supervisord.conf
    destination: /home/ubuntu
  - source: /requirements.txt
    destination: /home/ubuntu
  - source: /requirements/
    destination: /home/ubuntu/requirements

permissions:
  - object: /home/ubuntu/manage.py
    owner: ubuntu
    mode: 644
    type:
      - file
  - object: /home/ubuntu/supervisord.conf
    owner: ec2-user
    mode: 644
    type:
      - file
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
