# Generated by Django 4.2.6 on 2024-09-18 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apps_farms", "0001_initial"),
        ("apps_profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="profile_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_farm",
                to="apps_profiles.profile",
            ),
        ),
    ]
