# Generated by Django 4.2.6 on 2024-09-18 22:29

import apps.farms.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_farms", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="photo",
            field=models.URLField(
                default="/images/granja.jpg",
                max_length=500,
                validators=[apps.farms.models.file_validation],
            ),
        ),
    ]
