# Generated by Django 4.2.6 on 2024-09-19 01:59

import apps.rabbits.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_rabbits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rabbit",
            name="photo",
            field=models.URLField(
                default="/images/conejo.jpg",
                max_length=500,
                validators=[apps.rabbits.models.file_validation],
            ),
        ),
    ]
